language: perl

perl:
- "5.26"

dist: bionic

install:
- travis_retry sudo apt-get update -q
- travis_retry sudo apt-get install -y autoconf sed
- travis_retry sudo apt-get install -y `autoconf --trace 'PDFLBR_CHECK_PERL_MODULE:$2' | sed 's/,//g'`

before_script:
- perl '-V:.*'

script:
- ./bootstrap
- ./configure
- make

after_failure:
- test ! -f ./config.log || cat ./config.log
