.TH FMDT 1 "@DATE@" "Release @VERSION@" "@PACKAGE@"

.SH NAME
fmdt \- file metadata tools.

.SH SYNOPSIS

.TP
\fBfmdt\fP \fB\-h\fP|\fB\-\-help\fP
Display this help message.

.TP
\fBfmdt\fP pdf \fIaction\fP [\fIoptions\fP]...
PDF file metadata tools.

.SH PDF ACTIONS

.TP
\fIedit\fP {\fIfiles\fP|\fIdirectories\fP}...
Read BibTeX bibliographic data from PDF \fIfiles\fP, or PDF files within \fIdirectories\fP, and write to a temporary file.
This file is then opened in an editing program, given either by the \fI$VISUAL\fP or \fI$EDITOR\fP environment variables, or else the program `@fallback_editor@'.
Any modifications are then written back to the PDF files given by the \fIfile\fP field in each BibTeX entry.

.TP
\fIexport\fP [\fB\-e\fP|\fB\-\-exclude\fP \fIBibTeX-field\fP]... {\fIfiles\fP|\fIdirectories\fP}...
Read BibTeX bibliographic data from PDF \fIfiles\fP, or PDF files within \fIdirectories\fP, and print to standard output.
Any \fIBibTeX-field\fPs given to \fB\-\-exclude\fP are removed before printing.

.TP
\fIadd\fP {\fIfiles\fP|\fIdirectories\fP}...
Add PDF \fIfiles\fP, or PDF files within \fIdirectories\fP, to the PDF library, usually organised under `~/PDFLibrary'.

.TP
\fIremove\fP [\fB\-r\fP|\fB\-\-remove\-to\fP \fIdirectory\fP] {\fIlibrary files\fP|\fIlibrary directories\fP}...
Remove PDF \fIfiles\fP, or PDF files within \fIdirectories\fP, from the PDF library.
Copies of the removed PDF files are saved to the \fIdirectory\fP given by \fB\-\-remove\-to\fP, which default to the system temporary directory, e.g. `/tmp'.
