name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            sudo apt-get update -y || exit 1
            sudo apt-get install -y autoconf sed ghostscript poppler-utils perl-base || exit 1
            sudo apt-get install -y `autoconf --trace 'PDFLBR_CHECK_PERL_MODULE:$2' | sed 's/,//g'` || exit 1
      - name: Show Perl configuration
        run: |
          perl '-V:.*'
      - name: Configure
        run: |
          ./bootstrap
          if ! ./configure; then
            cat ./config.log
            exit 1
          fi
      - name: Build
        run: |
          make
